driver:
  enabled: false
toolkit:
  enabled: true
  env:
    - name: CONTAINER_RUNTIME
      value: containerd

daemonsets:
  nodeSelector:
    kubernetes.io/hostname: userver2
  
operator:
  defaultRuntime: containerd
  validator:
    repository: nvcr.io/nvidia/cloud-native
    image: gpu-operator-validator

devicePlugin:
  config:
    create: false  
    name: "rtx-2070"   
    default: "rtx-2070"