
alertmanager:
  alertmanagerSpec:
    replicas: 1

    nodeSelector:
      role: monitoring

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    storage: 
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

grafana:
  replicas: 1

  nodeSelector:
      role: monitoring

  # expect secret to be created
  admin:
    existingSecret: grafana-admin-creds
    userKey: admin-user
    passwordKey: admin-password

  lookupVolumeName: false

  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: true
    storageClassName: microk8s-hostpath
    accessModes:
      - ReadWriteOnce
    size: 15Gi

  annotations:
      argocd.argoproj.io/sync-options: Replace=false

prometheus:
  prometheusSpec:
    replicas: 1
    remoteWriteDashboards: false
    retention: 3d
    retentionSize: "20GB"

    nodeSelector:
      role: monitoring

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: microk8s-hostpath
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 4Gi
        cpu: 2

kube-state-metrics:
  nodeSelector:
    role: monitoring

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

nodeExporter:
  hostRootFsMount:
    enabled: false