apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.175
  share: /mnt/storage/k8s-nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1