---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBTQt3XQ7EAbFrTaIgpsxtVvEpaHABzAO6odrmmiUovZoHhoVLaZX5auUZ0kQfkUm8DvlO6U0NBRcllztQI1wSEhyu7FOqnKHMnZaieDL/hNHvOyq2rPtdCFmSWiDJR0rGsOYSq8MmUqEWYTBnVv1k4oR9sMGvNrcZ3OlFpzTXfHqyPGdC/SPfiKzAZRA2hJCAheYgx5yLVkaLjK7DeAnloXOs6LWNJn+9CRzeiaNCwpkdSlVC81FU8ylctt49KT8Po4pkegFw19s7/eT6nBnj7N3wn2krLCbPbIm7PU/VB6XAiLa0g8Z6ujfXxZQS75jR1tomjMx0bWGjw7BzI7KhheZy/dc1H99eLM32fSUtTVbh34Otbg+tA8Mmhp/l0RpSb3ChZ0LskJUCYS9LCk8uowvCsZXIxXZtiYl8XMlyJNS35qJWkF96vxtBMmHtpADpDYZBZ6wj8C7g8TN/3TarWJHdGOLCe/l64a0rdNakAm9ngi4Fyk7b4Pi6pgatA7XTITBjsfHjppvTqcjhxRhEMzNRBdXRhlh3rGUfSPyisxW/dDCbL/VL48y8L4aIUarAcA8OzHi7LJq/RT930VkjlSAobINMwcCtVf/KDtZyjCpzqVqAkBHt0Fsb/JAPauW0lhpoQLdipnb2EsahUASK2LojvBW+ryhPZRLzpHPyplUA8eR7ZXgq3GbwU9rZCYrgBFRRdyQc7WA==
    username: AgBhqiWfDrp668sjEuPnLQkRDlYrSo7h00416SCf4lYlXPHiPjmuGZD01BM+O0naUo/PYzR3EfVphWlkQFyTjjRjQEdxHwGBpy27qO1zNU0/YFeGiz9/OcVD1pF1RbwU6YsNEuOqGLfbTJcO9H1PhpY4X6gXgW9jiM8BCNMlMd6ZCfKksiFrlinM6jGnBDClu5dwjomkSS9/v3BpgSySJVrFfx4prZqviVrxSHTHxD2ZRPEZ8SQDp2MI/O/n8LlUFWcrPPopqbtUJDpNKtW6bCeEw/mCODNIaTl2JXed/RrRg1gWwRaFC9N5yzB6klECIieD9MyxYqBwwTO4yNS+9h6cK9lD0aHxhfsYe/QvN1NdaUOITs6J/VNmjyjNFKxYejdKhTJWdPpJ+i0HqIBLdnBWQFX7gxLftimXR1SYpiSD2etosdg9cg8ttd7aM062/MHU2WHvVUsJ7EFCEbX1FkAEq0iokvK/3RQLWtg04KxJHQvrdEbuxd5rBMmTErtQzDcuqtRlXpoafXSUFjBO3VkFATw4765lQ38ZqBsxvzGMjxhmdH5aDY9W+nMV4RlNdHMG+/DEVgKreymU9odew6EMcQl75/l12cDxBtjKhXeFfMIl48OBjHPkFpGKkGDB4d9VixsejjtwrapoI2TmhmSqZ7fxpqkxofBUisiOIKnmQKCGNdoe0ZqTI0IkZ7bZulFu9nPm
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
